#!/usr/bin/env php
<?php

foreach (array(__DIR__ . '/../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/vendor/autoload.php') as $file) {
    if (file_exists($file)) {
        require $file;
        break;
    }
}

$repoPath  = $argv[1];
$iniConfig = parse_ini_file(
    sprintf(
        '%s/.git/config',
        $repoPath
    ),
    true
);
$repoUrl   = $iniConfig['remote origin']['url'];
$repoUrl   = str_replace(
    [':', 'git@', '.git',],
    ['/', 'https://', '/'],
    $repoUrl
);

$openCommand = sprintf('open "%smerge_requests/new?merge_request[source_branch]="$(git rev-parse --abbrev-ref HEAD) -a "Google Chrome"', $repoUrl);
exec($openCommand);
